export const FETCH_AUTHORS_REQUESTED =
  'authorsList/FETCH_AUTHORS_REQUESTED'
export const FETCH_AUTHORS_SUCCEEDED =
  'authorsList/FETCH_AUTHORS_SUCCEEDED'
export const FETCH_AUTHORS_FAILED =
  'authorsList/FETCH_AUTHORS_FAILED'
